# Generated by Django 3.2 on 2021-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plasmabank',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
