# Generated by Django 3.2 on 2021-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210522_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
